# wheel visual properties 
wheel_radius: "0.08"
wheel_thickness: "0.04"
wheel_separation: "0.45"
wheel_color: "0 0 0 1"
# base visual properties 
base_length: "0.60"
base_width: "0.50"
base_height: "0.049338"
base_elevation: "0.00"
package_name: "amr_coco_description"
base_mesh_path: "meshes/coco_body.stl"
base_mesh_z_offset: "0.018"
base_color: "1 1 1 1"
# castor visual properties 
castor_radius: "0.049338"
castor_thickness: "0.02"
castor_separation_x: "0.3"
castor_separation_y: "0.35"
castor_color: "0.5 0.5 0 1" 

  